apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    tier: frontend
spec:
  ports:
    - targetPort: 5432
      port: 5432
   selector:
      name: postgres-app-pod
      labels:
       app: postgres-app