apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deploy
  labels:
    tier: frontend
spec:
  replicas: 2
  template:
    metadata:
      name: redis-app-pod
      labels:
       app: redis-app
    spec:
      containers:
      - name: redis-app
        image: redis
        ports:
          - containerPort: 6379
  selector:
    matchLabels:
      name: redis-app-pod
      labels:
       app: redis-app