apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: result-app-pod
    labels:
      app: result-app