apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    tier: frontend
spec:
  replicas: 2
  template:
    metadata:
      name: result-app-pod
      labels:
       app: result-app
       name: example
    spec:
      containers:
      - name: result-app
        image: dockersamples/examplevotingapp_result
        ports:
          - containerPort: 80
  selector:
    matchLabels:
       app: result-app
       name: example