apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 85
  selector:
    app: voting-app
    name: example
