apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      name: voting-app-pod
      labels:
       app: voting-app
    spec:
      containers:
      - name: voting-app
        image: dockersamples/examplevotingapp_vote
        ports:
          - containerPort: 80
  selector:
    matchLabels:
       app: voting-app


