apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: voting-app-pod
    labels:
      app: voting-app
