apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deploy
  labels:
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      name: worker-app-pod
      labels:
       app: worker-app
       name: example
    spec:
      containers:
      - name: worker-app
        image: dockersamples/examplevotingapp_worker
  selector:
    matchLabels:
       app: worker-app
       name: example